### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by kenuna** [Vaimer9/py-rpc#1]
On start main.py:

```
Traceback (most recent call last):
  File "c:\Users\VladOS\Desktop\bots\dsrpc\main.py", line 47, in <module>
    client.update(state=state,
  File "C:\Users\VladOS\AppData\Local\Programs\Python\Python311\Lib\site-packages\pypresence\presence.py", line 36, in update
    return self.loop.run_until_complete(self.read_output())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VladOS\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\VladOS\AppData\Local\Programs\Python\Python311\Lib\site-packages\pypresence\baseclient.py", line 88, in read_output
    raise ServerError(payload["data"]["message"])
pypresence.exceptions.ServerError: Child "activity" fails because child "details" fails because "details" length must be at least 2 characters long
```

**Comment by kenuna** [comment]
and my config.json:
```
{
	"id": ???,

	"attributes": {
		"state": "test ",
		"details": "1",
		"large_image": "telegram_messengersd",
		"small_image": "python-logo",
		"large_image_tooltip": "sus",
		"small_image_tooltip": ""
	},

	"button_attributes": {
		"button1": [

			{"label": "1"},
			{"url": "https://test.com"}
		],
		"button2": [
			{"label": "placeholder"},
			{"url": "placeholder"}
		]
	}
}

```

**Comment by Vaimer9** [comment]
You have to put your Application ID in the `"id"`. So just replace the `???` with your Application ID
